inner_only:
  title: Penny Park
  logo: logo.png

polygon:
  title: Polygon Land
  symbol: PL
  land_order: 1
  color: "#cc00ff"
  order: [pentagon, square, circle, hexagon, triangle, ellipse, octagon, diamond]
  assignments:
    pentagon:
      puzzle: _emoji
    square:
      puzzle: _multi_4
    circle:
      puzzle: _
    hexagon:
      puzzle: _
    triangle:
      puzzle: _
    ellipse:
      puzzle: _
    octagon:
      puzzle: _
    diamond:
      puzzle: _
